name: Greet User

on:
  
  workflow_dispatch:
  
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Get User Name
        uses: anmol098/name-to-github-username@v1.0
        id: get_username
      - name: Update README
        run: |
          sed -i "1s/^/Hello ${steps.get_username.outputs.username}! Welcome to my GitHub profile. :wave:\n\n/" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Added greeting message to README"
          git push
