name: Greet User

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Update README
        run: |
          sed -i "1s/^/Hello there! Welcome to my GitHub profile. :wave:\n\n/" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Added greeting message to README"
          git push
